baseURL = "https://adarshsprabhakaran.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
theme = "blowfish"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
title = "Pathfinder"